/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Notas;

import javax.swing.JOptionPane;

/**
 *
 * @author Joao
 */
public class Calculo extends javax.swing.JFrame {
Informacoes objPessoaJuridica = new Informacoes();
    /**
     * Creates new form Calculo
     */
    public Calculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBGraduacao = new javax.swing.JRadioButton();
        jBPosGraduacao = new javax.swing.JRadioButton();
        jBDoutorado = new javax.swing.JRadioButton();
        jBMedia = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTProva1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTProva2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBGraduacao.setText("Graduaçao");

        jBPosGraduacao.setText("Pos-Graduaçao");

        jBDoutorado.setText("Doutorado");

        jBMedia.setText("Calcular Media");
        jBMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMediaActionPerformed(evt);
            }
        });

        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Numero da Matricula");

        jLabel3.setText("Nota 1 Prova");

        jLabel4.setText("Nota 2 Prova");

        jLabel5.setText("Tipos de curso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(226, 226, 226))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTProva1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(271, 271, 271)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(jTProva2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jBGraduacao)
                            .addComponent(jBPosGraduacao)
                            .addComponent(jBDoutorado))))
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jBMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel3)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGraduacao)
                    .addComponent(jTMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jBPosGraduacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBDoutorado)
                        .addComponent(jTProva2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTProva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBMedia)
                            .addComponent(jBLimpar)
                            .addComponent(jBSair))))
                .addGap(18, 111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMediaActionPerformed
        // TODO add your handling code here:

        String numeroAluno, nomeAluno, n1, n2;

        objPessoaJuridica.setnome(jTNome.getText());
        objPessoaJuridica.setmatricula(jTMatricula.getText());

        numeroAluno = objPessoaJuridica.retorna_matricula();
        nomeAluno = objPessoaJuridica.retorna_nome();

        n1 = jTProva1.getText();
        n2 = jTProva2.getText();

        double numero1 = Double.parseDouble(n1);
        double numero2 = Double.parseDouble(n2);

        double media = (numero1 + numero2) /2 ;

        if (jBGraduacao.isSelected()){
            if (media > 7){
                JOptionPane.showMessageDialog(null, " - nome:  " + "  Graduaçao  " + nomeAluno + " - numero da matricula:  " + numeroAluno + " - Media: " + media + " - Aprovado");
            }
            else if(media < 7){
                JOptionPane.showMessageDialog(null,  " - nome:  " + "  Pos Graduaçao  " + nomeAluno + " - numero da matricula:  " + numeroAluno + " - Media: " + media + " - Recuperaçao");
            }
            else{
                JOptionPane.showMessageDialog(null, " - nome:  " + "  Graduaçao  " + nomeAluno + " - numero da matricula:  " + numeroAluno + " - Media: " + media + " - Reprovado");
            }
        }
        if (jBPosGraduacao.isSelected()){
            if (media > 6){
                JOptionPane.showMessageDialog(null, " - nome:  " + "  Pos Graduaçao  " + nomeAluno + " - numero da matricula:  " + numeroAluno + " - Media: " + media + " - Aprovado");
            }
            else if(media < 6){
                JOptionPane.showMessageDialog(null,  " - nome:  " + "  Pos Graduaçao  " + nomeAluno + " - numero da matricula:  " + numeroAluno + " - Media: " + media + " - Recuperaçao");
            }
            else{
                JOptionPane.showMessageDialog(null, " - nome:  " + "  Pos Graduaçao  " + nomeAluno + " - numero da matricula:  " + numeroAluno + " - Media: " + media + " - Reprovado");
            }
        }
        if(jBDoutorado.isSelected()){
            if(media > 5){
                JOptionPane.showMessageDialog(null, " - nome:  " + "  Doutorado  " + nomeAluno + " - numero da matricula:  " + numeroAluno + " - Media: " + media + " - Aprovado");
            }
            else if(media < 5){
                JOptionPane.showMessageDialog(null,  " - nome:  " + "  Pos Graduaçao  " + nomeAluno + " - numero da matricula:  " + numeroAluno + " - Media: " + media + " - Recuperaçao");
            }
            else{
                JOptionPane.showMessageDialog(null, " - nome:  " +  "  Doutorado  " + nomeAluno + " - numero da matricula:  " + numeroAluno + " - Media: " + media + " - Reprovado");
            }
        }
    }//GEN-LAST:event_jBMediaActionPerformed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        // TODO add your handling code here:
        jTNome.setText(null);
        jTMatricula.setText(null);
        jTProva1.setText(null);
        jTProva2.setText(null);
        jTNome.requestFocus();
    }//GEN-LAST:event_jBLimparActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jBDoutorado;
    private javax.swing.JRadioButton jBGraduacao;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBMedia;
    private javax.swing.JRadioButton jBPosGraduacao;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTMatricula;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTProva1;
    private javax.swing.JTextField jTProva2;
    // End of variables declaration//GEN-END:variables
}
